version: '3'
services:
  mongodb:
    image: mongo:3.6.0
    ports:
      - "27017:27017"
    volumes:
      - dbvolume:/data
    environment: {
      AUTH: "no"
    }
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - "6379:6379"
volumes:
  dbvolume: {}
